// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AButton: typeof import("ant-design-vue/es")["Button"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElFooter: typeof import("element-plus/es")["ElFooter"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    HelloWorld: typeof import("./components/HelloWorld.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    UsePinia: typeof import("./components/usePinia.vue")["default"];
  }
}
